import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../components/Header";
import BannerCaraousel from "@/components/BannerCaraousel";
import InvestBanner from "@/components/InvestBanner";
import ExploreSection from "@/components/ExploreSection";
import LowerBanner from "@/components/LowerBanner";
import BottomNav from "@/components/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Digital Gold</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          background: "linear-gradient(45deg, #7a6ddd, #321fbd, #6740d3)",
        }}
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <main>
          <InvestBanner />
          <BannerCaraousel />
          <ExploreSection />
          <LowerBanner />
        </main>
        <BottomNav />
      </div>
    </>
  );
}
